/**
 * Copy brand/tokens.css into the app before dev/build.
 *
 * brand/tokens.css stays the single source of truth (ADR-004). Importing it
 * across the workspace boundary directly is what we tried first: Turbopack
 * roots the filesystem at the Next project, so `../../../../brand/tokens.css`
 * fails with "leaves the filesystem root". Pointing Turbopack at the repo root
 * would fix the import and make the whole monorepo the project, which is a
 * worse trade for build time and for Vercel's root-directory setting.
 *
 * So: copy, but never by hand and never checked in. The generated file is
 * gitignored and regenerated by predev/prebuild, so it cannot drift from the
 * source the way a pasted palette would.
 */
import { copyFileSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const source = resolve(here, "../../../brand/tokens.css");
const target = resolve(here, "../src/app/brand.generated.css");

if (!existsSync(source)) {
  console.error(`sync-brand: cannot find ${source}`);
  process.exit(1);
}

const header = `/* GENERATED by scripts/sync-brand.mjs from brand/tokens.css — do not edit.
 * Edit brand/tokens.css instead; this file is rewritten on every dev/build. */\n\n`;

writeFileSync(target, header + readFileSync(source, "utf8"));
void copyFileSync;
void join;
console.log("sync-brand: brand/tokens.css -> src/app/brand.generated.css");
