/**
 * Copy brand/tokens.css and the brand marks into the app before dev/build.
 *
 * brand/tokens.css stays the single source of truth (ADR-004). Importing it
 * across the workspace boundary directly is what we tried first: Turbopack
 * roots the filesystem at the Next project, so `../../../../brand/tokens.css`
 * fails with "leaves the filesystem root". Pointing Turbopack at the repo root
 * would fix the import and make the whole monorepo the project, which is a
 * worse trade for build time and for Vercel's root-directory setting.
 *
 * So: copy, but never by hand and never checked in. Generated files are
 * gitignored and regenerated by predev/prebuild, so none of them can drift
 * from the source the way a pasted palette or a hand-copied SVG would.
 *
 * `favicon.svg` lands at `src/app/icon.svg` — the exact filename Next's App
 * Router metadata convention looks for, so it is served as the favicon with
 * no manual `<link>` and no separately-maintained `.ico`. `logo.svg` and
 * `logotype.svg` land in `public/brand/` for the few places a static file
 * reference is enough (touch icons, social preview); the nav rail and the
 * landing hero use their own inline copy instead
 * (`src/components/ui/logo.tsx`) because animating an SVG with `motion`
 * needs its markup in the React tree, not behind an `<img src>`.
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const brandDir = resolve(here, "../../../brand");
const appDir = resolve(here, "../src/app");
const publicBrandDir = resolve(here, "../public/brand");

function requireSource(path) {
  if (!existsSync(path)) {
    console.error(`sync-brand: cannot find ${path}`);
    process.exit(1);
  }
  return path;
}

// tokens.css -> brand.generated.css, with a do-not-edit header.
const tokensSource = requireSource(resolve(brandDir, "tokens.css"));
const tokensHeader = `/* GENERATED by scripts/sync-brand.mjs from brand/tokens.css — do not edit.
 * Edit brand/tokens.css instead; this file is rewritten on every dev/build. */\n\n`;
writeFileSync(
  resolve(appDir, "brand.generated.css"),
  tokensHeader + readFileSync(tokensSource, "utf8"),
);

// favicon.svg -> app/icon.svg (Next App Router favicon convention).
copyFileSync(requireSource(resolve(brandDir, "favicon.svg")), resolve(appDir, "icon.svg"));

// logo.svg / logotype.svg -> public/brand/, for static (non-animated) refs.
mkdirSync(publicBrandDir, { recursive: true });
copyFileSync(requireSource(resolve(brandDir, "logo.svg")), resolve(publicBrandDir, "logo.svg"));
copyFileSync(
  requireSource(resolve(brandDir, "logotype.svg")),
  resolve(publicBrandDir, "logotype.svg"),
);

console.log(
  "sync-brand: tokens.css -> brand.generated.css, favicon.svg -> icon.svg, " +
    "logo(type).svg -> public/brand/",
);
